Fix add model
jasp-stats/jaspProcess pull request #100
Opened 2024-05-30 13:49 UTC by maltelueken

Fixes #99 by recreating the model graphs every time the analysis is run. This is necessary because the graphs are modified later (dummy variables and interaction terms are added). The modifications need to run every time because they also add additional variables to the dataset which is reloaded at every run. This is the simplest solution even and recreating the model graphs leads to very little computational overhead. For the future, decoupling the dataset modifications from the model modifications might be a better option, but this would create some overhead too.

Also restricts the dependent variable to be ordinal or scale type (which both are converted to `numeric` in R) because lavaan currently cannot handle categorical outcomes.

2024-06-03 13:20 UTC, JohnnyDoorn requested changes
Looks good - one suggestion: change the header of the plots option:
Path Plots -> Statistical Path Plots
because the checkboxes there are only for the statistical plots, and not the conceptual ones, right?

2024-06-03 14:18 UTC, maltelueken commented
I can remove the indentation, but greying out the boxes will be difficult because they apply to all models (and some might have a statistical plot, others not).

2024-06-03 14:19 UTC, JohnnyDoorn commented
OK, in that case changing the group name ( Path Plots -> Statistical Path Plots) and removing the indentation should be clear enough

2024-06-04 09:53 UTC, JohnnyDoorn approved these changes

2024-06-04 09:53 UTC, merged

2024-06-04 11:20 UTC, JohnnyDoorn commented
Btw @maltelueken  it still seems like the input boxes fall off the screen - is that fixed somewhere else? 
![image](https://github.com/jasp-stats/jaspProcess/assets/15704203/05303e1d-4348-42c2-8d37-64ed8fff4087)

2024-06-04 13:16 UTC, maltelueken commented
@boutinb said that he would fix this, otherwise, I also found a solution in https://github.com/jasp-stats/INTERNAL-jasp/issues/2533 which I could use instead.